In [1]:
# Data: https://www.kaggle.com/datasets/mfaisalqureshi/spam-email

In [2]:
import numpy as np
import pandas as pd

In [3]:
df1 = pd.read_csv("mail_data.csv")
df1.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df1.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [5]:
df1.isnull().sum()

Category    0
Message     0
dtype: int64

In [6]:
df1.shape

(5572, 2)

In [7]:
df1['spam']=df1['Category'].apply(lambda x: 1 if x=='spam' else 0)
df1.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
df1.groupby('spam').describe()

Category                    Message         \
        count unique   top  freq   count unique   
spam                                              
0        4825      1   ham  4825    4825   4516   
1         747      1  spam   747     747    641   

                                                              
                                                    top freq  
spam                                                          
0                                Sorry, I'll call later   30  
1     Please call our customer service representativ...    4

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Anuj
[nltk_data]     Verma\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [10]:
len(df1)

5572

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
def edit_message(message):
    edited_message = re.sub('[^a-zA-Z]',' ',message)
    edited_message = edited_message.lower()
    edited_message = edited_message.split()
    edited_message = [ps.stem(word) for word in edited_message if not word in stopwords.words('english')]
    edited_message = ' '.join(edited_message)
    return edited_message
for i in range(0, len(df1)):
    edited_message = edit_message(df1['Message'][i])
    corpus.append(edited_message)

In [12]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [13]:
words = []
for message in corpus:
    words = words + message.split()
words

['go',
 'jurong',
 'point',
 'crazi',
 'avail',
 'bugi',
 'n',
 'great',
 'world',
 'la',
 'e',
 'buffet',
 'cine',
 'got',
 'amor',
 'wat',
 'ok',
 'lar',
 'joke',
 'wif',
 'u',
 'oni',
 'free',
 'entri',
 'wkli',
 'comp',
 'win',
 'fa',
 'cup',
 'final',
 'tkt',
 'st',
 'may',
 'text',
 'fa',
 'receiv',
 'entri',
 'question',
 'std',
 'txt',
 'rate',
 'c',
 'appli',
 'u',
 'dun',
 'say',
 'earli',
 'hor',
 'u',
 'c',
 'alreadi',
 'say',
 'nah',
 'think',
 'goe',
 'usf',
 'live',
 'around',
 'though',
 'freemsg',
 'hey',
 'darl',
 'week',
 'word',
 'back',
 'like',
 'fun',
 'still',
 'tb',
 'ok',
 'xxx',
 'std',
 'chg',
 'send',
 'rcv',
 'even',
 'brother',
 'like',
 'speak',
 'treat',
 'like',
 'aid',
 'patent',
 'per',
 'request',
 'mell',
 'mell',
 'oru',
 'minnaminungint',
 'nurungu',
 'vettam',
 'set',
 'callertun',
 'caller',
 'press',
 'copi',
 'friend',
 'callertun',
 'winner',
 'valu',
 'network',
 'custom',
 'select',
 'receivea',
 'prize',
 'reward',
 'claim',
 'call',
 'cl

In [14]:
len(words)

50282

In [15]:
Bag_of_words = set(words)
len(Bag_of_words)

6314

In [39]:
# from collections import Counter
# dictionary = Counter(words)
# sorted(dictionary.items(), key=lambda pair: pair[1], reverse=True)

In [42]:
# len(dictionary)

In [19]:
from sklearn.feature_extraction.text import CountVectorizer
CV = CountVectorizer(vocabulary = Bag_of_words)
X = CV.fit_transform(corpus).toarray()

In [20]:
Y = df1.spam

In [21]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
X.shape, Y.shape 

((5572, 6314), (5572,))

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 10)

In [24]:
X.shape, X_train.shape, X_test.shape

((5572, 6314), (4457, 6314), (1115, 6314))

In [25]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train,Y_train)

MultinomialNB()

In [26]:
X_train_score = model.score(X_train, Y_train)
X_train_score

0.9923715503702042

In [27]:
X_test_score = model.score(X_test, Y_test)        
X_test_score                                      

0.9766816143497757

In [28]:
from sklearn.metrics import confusion_matrix
Y_pred = model.predict(X_test)
conf_matrix = confusion_matrix(Y_test, Y_pred)
conf_matrix    
# (1,1)-True Negative, (1,2)-False Positive, (2,1)-False Negative, (2,2)-True Positive

array([[955,  17],
       [  9, 134]], dtype=int64)

In [29]:
emails = ['I saw your profile on Linkedin. You seem to be fit for the job. Would you like to join from next Monday?',
           'This Diwali, a huge sale is out. 50% discount on each item. Place your order before the stock is empty.']
email_data_features = CV.fit_transform(emails).toarray()
email_prediction = model.predict(email_data_features)
email_prediction

array([0, 1], dtype=int64)

In [30]:
# Using Pipeline Methos

In [31]:
X = df1.Message
Y = df1.spam

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 10)

In [33]:
from sklearn.pipeline import Pipeline
classifier = Pipeline([
    ('vectorizer',  CountVectorizer(vocabulary = Bag_of_words)),
    ('nb', MultinomialNB())
])

In [34]:
classifier.fit(X_train, Y_train)

Pipeline(steps=[('vectorizer',
                 CountVectorizer(vocabulary={'aa', 'aah', 'aaniy',
                                             'aaooooright', 'aathi', 'ab',
                                             'abbey', 'abdomen', 'abeg', 'abel',
                                             'aberdeen', 'abi', 'abil',
                                             'abiola', 'abj', 'abl', 'abnorm',
                                             'abouta', 'abroad', 'absenc',
                                             'absolut', 'absolutli', 'abstract',
                                             'abt', 'abta', 'aburo', 'abus',
                                             'ac', 'academ', 'acc', ...})),
                ('nb', MultinomialNB())])

In [35]:
classifier.score(X_train, Y_train)

0.9847431007404084

In [36]:
classifier.score(X_test, Y_test)

0.9704035874439462

In [37]:
emails = ['This Diwali, a huge sale is out. 50% discount on each item. Place your order before the stock is empty.',
           'I saw your profile on Linkedin. You seem to be fit for the job. Would you like to join from next Monday? ']
classifier.predict(emails)

array([1, 0], dtype=int64)

In [38]:
mis_cals = ['Your order is ready to be dispatched.',
            'Hi, Vivek! Your order is ready to be dispatched.']
classifier.predict(mis_cals)

array([1, 0], dtype=int64)